### PR TITLE
Fix Xcode 9 warnings

### PR DESCRIPTION
**Pull request by brightsider**

### CODE REVIEW

**Comment by macdoum1** [comment]
Would love to silence these warnings in our project!

**Comment by rs** [comment]
Could please fix the conflicts do I can merge?

**Comment by macdoum1** [comment]
@rs Create another PR with the merge conflicts resolved: https://github.com/rs/SDAVAssetExportSession/pull/77

**Comment by brightsider** [comment]
@rs can you close pr and update podspec?

**Pull request closed without merging**
