### PR TITLE
Fix for exporting with custom timeRange

### PR DESCRIPTION
**Pull request by EliSchleifer**
Now supports scenario where timeRange does not match original asset
length perfectly (effectively supports trimming of original clip)

### CODE REVIEW

**Comment by ndbroadbent** [comment]
Hi, I'm just confirming that trimming with a different start time was still broken, and @tybu's fix works for me. @tybu - Would you still be able to submit a pull request? It would be really helpful for anyone else who comes across this library. If you don't have time, I would be happy to do it.

**Comment by tybu** [comment]
hi @ndbroadbent :)
@EliSchleifer proposed create a proper pull request. If we have no news, i can submit a pull request for this fix.

**Comment by EliSchleifer** [comment]
I believe this might still be broken. I had a local patch that was very
small. I suspect whatever you have cooked is nearly identical. Would be
good to fix in mainline

**Comment by yusuftor** [comment]
Using the timeRange, for example from 0 to 10 seconds, causes the export to be cancelled. Has anyone figured out a fix for this?

**Comment by mself** [comment]
How does this behavior compare to AVAssetExportSession?  If the source asset has a non-zero start time, does it create an asset that also has a non-zero start time?  Or does it shift all of the times so that the output always has a zero start time?

Also, if timeRange is specified, do those times refer to the original times of the source asset or the shifted time?  For example, if the input asset is from t=5 to t=30 and you specify a time range of t = 10 to t = 20, which part of the input asset is exported?

**Pull request closed without merging**
